const {getAllUsers}=require('../controllers/admin')
const {createEvent,getAllEvents, getEventById,updateEvent,deleteEvent}=require('../controllers/event')
const {sendNotification,getUserNotifications,markAsRead }=require('../controllers/notification')
const {createOrder ,getUserOrders} =require('../controllers/order')
const {processPayment}=require('../controllers/payment')
const {requestRefund,approveRefund,rejectRefund,getAllRefundRequests}=require('../controllers/refund');
const {purchaseTicket,getUserTickets}=require('../controllers/ticket')
const {createTicketType ,getTicketTypesByEvent,updateTicketType,deleteTicketType}=require('../controllers/tickettype')
const {registerUser,loginUser,getUserProfile}=require('../controllers/user')
const router=require('express').Router();

router.get('/admin/users',getAllUsers)
    .post('/events',createEvent)
    .get('/events',getAllEvents)
    .get('/events/:id',getEventById)
    .put('/events/:id',updateEvent)
    .delete('/deleteEvent/:id',deleteEvent)
    .post('/notification',sendNotification)
    .get('/notifications/user/:userId',getUserNotifications)
    .put('/notifications/:id/read',markAsRead)
    .post('/createorders',createOrder)
    .get('/orders/user/:userId',getUserOrders)
    .post('/payments',processPayment)
    .post('/refunds',requestRefund)
    .put('/refunds/:id/approve',approveRefund)
    .put('/refunds/:id/reject',rejectRefund)
    .get('/refunds',getAllRefundRequests)
    .post('/tickets/purchase',purchaseTicket)
    .get('/tickets/user/:userId',getUserTickets)
    .post('/ticket-types',createTicketType)
    .put('/ticket-types/:id',updateTicketType)
    .get('/ticket-types/event/:eventId',getTicketTypesByEvent)
    .delete('/deleteticket-types/:id',deleteTicketType)
    .post('/users/register',registerUser)
    .post('/users/login',loginUser)
    .get('/users/profile/:id',getUserProfile)

module.exports=router
